<?php

namespace MDOAgendaMoparmanBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DueDateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DueDateRepository extends EntityRepository
{
    public function findAll()
    {
        return $this->findBy(array(), array('due_date' => 'ASC'));
    }
}
