<?php

namespace MDOAgendaMoparmanBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VehicleCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VehicleCategoryRepository extends EntityRepository
{
}
