MDOAgendaMoparmanBundle\Entity\Category:
    type: entity
    table: null
    repositoryClass: MDOAgendaMoparmanBundle\Entity\CategoryRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
    lifecycleCallbacks: {  }
    manyToMany:
            contacts:
                targetEntity: Contact
                mappedBy: category
