MDOAgendaMoparmanBundle\Entity\Contact:
    type: entity
    table: null
    repositoryClass: MDOAgendaMoparmanBundle\Entity\ContactRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        email:
            type: string
            length: 255
            nullable: true
        phone:
            type: string
            length: 255
            nullable: true
        address:
            type: string
            length: 255
            nullable: true
        city:
            type: string
            length: 255
            nullable: true
        notes:
            type: text
        photo:
            type: string
            length: 255
        categories:
            type: array
    lifecycleCallbacks: {  }
    manyToMany:
            category:
                targetEntity: Category
                inversedBy: contacts
            vehicle:
                targetEntity: Vehicle
                inversedBy: owner
            picture:
                targetEntity: Picture
                inversedBy: pictures
                nullable: true
