MDOAgendaMoparmanBundle\Entity\VehicleCategory:
    type: entity
    table: null
    repositoryClass: MDOAgendaMoparmanBundle\Entity\VehicleCategoryRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
    manyToMany:
            vehicles:
                targetEntity: Vehicle
                inversedBy: categories